export type UiLang = "en" | "fa";

export function detectUiLang(): UiLang {
  if (typeof navigator === "undefined") return "en";
  const lang = (navigator.language || "en").toLowerCase();
  return lang.startsWith("fa") || lang.startsWith("ar") ? "fa" : "en";
}

export const COPY = {
  en: {
    brand: "Grok",
    product: "Voice",
    tagline: "Talk to Grok",
    hint: "Tap the orb to start a live conversation",
    start: "Start conversation",
    connecting: "Connecting…",
    listening: "Listening",
    thinking: "Thinking",
    speaking: "Speaking",
    muted: "Muted",
    ended: "Call ended",
    close: "Close",
    mute: "Mute",
    unmute: "Unmute",
    hangup: "End",
    history: "Transcript",
    keyboard: "Type",
    voices: "Voices",
    language: "Language",
    auto: "Auto",
    english: "English",
    persian: "Persian",
    typePlaceholder: "Message Grok",
    send: "Send",
    emptyHistory: "The conversation will appear here.",
    micDenied: "Microphone access is needed to talk. Allow it in the browser, then try again.",
    retry: "Try again",
    greeting: "Hey — I'm Grok. What's on your mind?",
    you: "You",
    grok: "Grok",
    pickVoice: "Choose a voice",
    about: "Realtime voice with Grok. Speak naturally — interrupt anytime.",
  },
  fa: {
    brand: "گروک",
    product: "صدا",
    tagline: "با گروک حرف بزن",
    hint: "برای شروع مکالمه زنده، کره را لمس کن",
    start: "شروع مکالمه",
    connecting: "در حال اتصال…",
    listening: "گوش می‌دهد",
    thinking: "در حال فکر",
    speaking: "در حال صحبت",
    muted: "بی‌صدا",
    ended: "تماس تمام شد",
    close: "بستن",
    mute: "قطع میکروفن",
    unmute: "وصل میکروفن",
    hangup: "پایان",
    history: "رونوشت",
    keyboard: "تایپ",
    voices: "صداها",
    language: "زبان",
    auto: "خودکار",
    english: "انگلیسی",
    persian: "فارسی",
    typePlaceholder: "پیام به گروک",
    send: "ارسال",
    emptyHistory: "مکالمه اینجا دیده می‌شود.",
    micDenied: "برای صحبت باید به میکروفن دسترسی بدهی. اجازه را در مرورگر فعال کن و دوباره تلاش کن.",
    retry: "تلاش دوباره",
    greeting: "سلام — من گروک‌ام. چی تو ذهنته؟",
    you: "شما",
    grok: "گروک",
    pickVoice: "انتخاب صدا",
    about: "مکالمه صوتی زنده با گروک. طبیعی حرف بزن — هر وقت خواستی قطعش کن.",
  },
} as const;
